name: Dockerize and Deploy

on:
  push:
    branches:
      - production

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: lsha0730/joker:latest
      - 
        name: Upload systemd service file
        uses: actions/upload-artifact@v3
        with:
          name: joker-service-file
          path: ./joker.service

  deploy:
    runs-on: self-hosted
    needs: dockerize

    steps:
    - name: Download systemd service file
      uses: actions/download-artifact@v3
      with:
        name: joker-service-file
        path: .

    - name: Pull Docker image
      run: docker pull lsha0730/joker:latest

    - name: Copy systemd service file
      run: sudo cp joker.service /etc/systemd/system/joker.service

    - name: Reload systemd daemon
      run: sudo systemctl daemon-reload

    - name: Enable and start Joker service
      run: |
        sudo systemctl enable joker
        sudo systemctl start joker

